routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::resource('budget', 'BudgetController');
});

app/Models/Budget.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Budget.
 *
 * @package namespace App\Models;
 */
class Budget extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'title',
        'description',
        'UAH',
        'USD',
        'created_at'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function budgets()
    {
        return $this->hasMany(Budget::class);
    }
}

app/Http/Controllers/BudgetController.php
<?php

namespace App\Http\Controllers;

use App\Services\BudgetService as Service;
use App\Http\Requests\Budget\Index;
use App\Http\Requests\Budget\Store;
use App\Http\Requests\Budget\Update;
use App\Http\Requests\Budget\Destroy;

class BudgetController extends Controller
{
    protected $service;

    public function __construct(Service $service)
    {
        $this->service = $service;
    }

    /**
     * @param Index $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Index $request)
    {
        $budgets = $this->service->get($request);
        return view('budget.index',
            is_array($budgets) ? $budgets : ['budgets' => $budgets]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('budget.create');
    }

    /**
     * @param Store $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(Store $request)
    {
        $this->service->store($request);
        return redirect('budget');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $budget = $this->service->show($id);
        return view('budget.show', [
            'budget' => $budget,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $budget = $this->service->show($id);
        return view('budget.edit', [
            'budget' => $budget,
        ]);
    }

    /**
     * @param Update $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(Update $request, $id)
    {
        $this->service->update($request, $id);
        return redirect()->route('budget.index');
    }

    /**
     * @param Destroy $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Destroy $request, $id)
    {
        $this->service->destroy($id);
        return redirect('budget');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/budget/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form action="{{ route('budget.store') }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('POST') }}

                    <div class="form-group">
                        <label for="title">Title</label>
                        <input name="title" type="text" class="form-control" id="title" placeholder="Title">
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" class="form-control" rows="3" id="description" placeholder="Description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="UAH">UAH</label>
                        <input name="UAH" type="text" class="form-control" id="UAH" placeholder="UAH">
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/budget/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form action="{{ route('budget.update', ['id' => $budget->id]) }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    <div class="form-group">
                        <label for="title">Title</label>
                        <input name="title" type="text" class="form-control" id="title" value="{{ $budget->title }}">
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" class="form-control" rows="3" id="description">
                            {{ $budget->description }}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label for="UAH">UAH</label>
                        <input name="UAH" type="text" class="form-control" id="UAH" value="{{ $budget->UAH }}">
                    </div>
                    <div class="form-group">
                        <label for="USD">USD</label>
                        <input name="USD" type="text" class="form-control" id="USD" value="{{ $budget->USD }}">
                    </div>

                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/budget/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-8">
                    <a href="{{ route('budget.create') }}" class="btn btn-success">Create</a>
                </div>
                <div class="col-md-4">
                    <form action="{{ route('budget.index') }}" method="GET">
                        <div class="form-group col-md-6">
                            <label>От: </label>
                            <input type="date" class="form-control" id="date" name="date_from" placeholder="Дата" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label>До: </label>
                            <input type="date" class="form-control" id="date" name="date_to" placeholder="Дата" required>
                        </div>
                        <div class="form-group col-md-12">
                            <button type="submit" class="form-control btn btn-primary">Get!</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <table class="table">
                    <caption>Budget</caption>
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>UAH</th>
                        <th>USD</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($budgets as $budget)
                        <tr>
                            <th>{{ $budget->id }}</th>
                            <td>{{ $budget->title }}</td>
                            <td>{{ $budget->description }}</td>
                            <td>{{ $budget->UAH }}</td>
                            <td>{{ $budget->USD }}</td>
                            <td><a href="{{ route('budget.show', ['id' => $budget->id]) }}"><i class="glyphicon glyphicon-eye-open"></i></a></td>
                            <td><a href="{{ route('budget.edit', ['id' => $budget->id]) }}"><i class="glyphicon glyphicon-pencil"></i></a></td>
                        </tr>
                    @endforeach
                    @if(isset($uah) && isset($usd))
                        <tr>
                            <th>Results</th>
                            <td></td>
                            <td></td>
                            <td><b>{{ $uah }}</b></td>
                            <td><b>{{ $usd }}</b></td>
                        </tr>
                    @endif
                    </tbody>
                </table>
                {{ $budgets->appends(request()->all())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/budget/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Title: </label>
                    <p>{{ $budget->title }}</p>
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <p>{{ $budget->description }}</p>
                </div>
                <div class="form-group">
                    <label>UAH</label>
                    <p>{{ $budget->UAH }}</p>
                </div>

                @if(!empty($budget->USD))
                    <div class="form-group">
                        <label>USD</label>
                        <p>{{ $budget->USD }}</p>
                    </div>
                @endif

                <a href="{{ route('budget.edit', ['id' => $budget->id]) }}" class="btn btn-primary" style="float: left; margin-right: 10px;"><i class="glyphicon glyphicon-pencil"></i></a>
                <form action="{{ route('budget.destroy', ['id' => $budget->id]) }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i></button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

</body>
</html>